apiVersion: v1
kind: Namespace
metadata:
  name: nsinit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-sa
  namespace: nsinit
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
  namespace: nsinit
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
  namespace: nsinit
subjects:
- kind: ServiceAccount
  name: default-ns-sa
  namespace: nsinit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-role
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: nsinit-controller
  namespace: nsinit
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: nsinit.adhol.io
    versionSelection:
      constraints: 0.1.0
  values:
  - secretRef:
      name: nsinit-config
---
apiVersion: v1
kind: Secret
metadata:
  name: nsinit-config
  namespace: nsinit
stringData:
  values.yml: |
    ---
    ns_create_action: 'print("Default ns_create_action invoked. But updated one")'
    ns_update_action: 'print("Default ns_update_action invoked. But updated one")'
