apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: nsinit.adhol.io.0.1.0
spec:
  refName: nsinit.adhol.io
  version: 0.1.0
  releaseNotes: |
    Initial release of the nsinit package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        svc_port:
          type: integer
          description: Port number for the service.
          default: 80
        app_port:
          type: integer
          description: Target port for the application.
          default: 80
        ns_create_action:
          type: string
          description: Starlark script used when namespace is created
          default: print("Default ns_create_action invoked")
        ns_update_action:
          type: string
          description: Starlark script used when namespace is updated
          default: print("Default ns_update_action invoked")
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: docker.io/adhol/nsinit:0.1.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
