apiVersion: v1
kind: Namespace
metadata:
  name: nsinit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-sa
  namespace: nsinit
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
  namespace: nsinit
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-sa-role-binding
  namespace: nsinit
subjects:
- kind: ServiceAccount
  name: default-ns-sa
  namespace: nsinit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role-binding
  namespace: nsinit
subjects:
- kind: ServiceAccount
  name: default
  namespace: nsinit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-role
